services:
  - type: web
    name: kani-game-center-api
    runtime: docker # .NET requires Docker on Render
    repo: https://github.com/Kananelo0207/kani-game-center # Replace with your repo URL
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile # Points to the Dockerfile in your subfolder
    envVars:
    - key: PORT
      value: 8080
    - key: ASPNETCORE_URLS
      value: http://+:8080
      - key: ASPNETCORE_ENVIRONMENT
        value: Production